### ISSUE TITLE
Data is missing certain special characters

### ISSUE THREAD

**Issue by aaroncadrian** [mikerovers/usb-barcode-scanner#1]
Whenever I scan a PDF417 barcode such as ```V=1,EID=12345```, I get ```V1EID12345``` from the data callback.  This issue occurs regardless of the barcode scanner device that I use.  

These characters do show up whenever I use the scanner as a normal HID device outside of Node.js, such as in Microsoft Word.

Special characters such as ```,``` ```=``` ```[``` and ```]``` are missing from the Default HID map.

**Comment by aaroncadrian** [comment]
#2 - I created a pull request where more characters were added to the default HID map.

**Comment by mikerovers** [comment]
Sorry for the late response. Looks good, thank you!
